name: Pre-commit Validation
on:
  pull_request:
    branches:
      - master

jobs:
  run-pre-commit:
    name: Run Pre-commit Hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit on all files
        run: |
          echo "Running pre-commit hooks on changed files..."
          echo "This catches bypassed hooks (--no-verify usage)"

          # Run pre-commit on all changed files between master and HEAD
          pre-commit run --from-ref origin/master --to-ref HEAD

      - name: Verify compliance
        run: |
          echo "✅ All pre-commit hooks passed"
          echo ""
          echo "This ensures code quality even if someone used --no-verify locally"
